# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2013
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
# Shu Muto <shu.mutow@gmail.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: glance VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2018-08-09 04:23+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2018-02-09 10:00+0000\n"
"Last-Translator: Shu Muto <shu.mutow@gmail.com>\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 4.3.3\n"
"Language-Team: Japanese\n"

#, python-format
msgid "\t%s"
msgstr "\t%s"

#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr "最後の RPC 呼び出しで %(cls)s 例外が発生しました: %(val)s"

#, python-format
msgid "%(m_id)s not found in the member list of the image %(i_id)s."
msgstr "イメージ %(i_id)s のメンバーリストで %(m_id)s が見つかりません。"

#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr "%(serv)s (pid %(pid)s) が実行中..."

#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr "%(serv)s は既に実行されている可能性があります: %(pid)s"

#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being used."
msgstr ""
"%(strategy)s はモジュールとして 2 回登録されています。%(module)s は使用されて"
"いません。"

#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Could not load the "
"filesystem store"
msgstr ""
"%(task_type)s の %(task_id)s が正しく設定されていません。ファイルシステムスト"
"アをロードできませんでした。"

#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Missing work dir: "
"%(work_dir)s"
msgstr ""
"%(task_type)s の %(task_id)s が適切に設定されていません。作業ディレクトリー "
"%(work_dir)s がありません"

#, python-format
msgid "%(verb)sing %(serv)s"
msgstr "%(serv)s の %(verb)s 中"

#, python-format
msgid "%(verb)sing %(serv)s with %(conf)s"
msgstr "%(conf)s を使用して %(serv)s を %(verb)s 中"

#, python-format
msgid ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in brackets "
"separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""
"%s host:port のペアを指定してください。host は IPv4 アドレス、IPv6 アドレス、"
"ホスト名、または FQDN です。IPv6 アドレスを使用する場合は、アドレスを大括弧で"
"囲んでポートと区別してください (例えば、\"[fe80::a:b:c]:9876\")。"

#, python-format
msgid "%s can't contain 4 byte unicode characters."
msgstr "%s に 4 バイトの Unicode 文字が含まれていてはなりません。"

#, python-format
msgid "%s is already stopped"
msgstr "%s は既に停止しています"

#, python-format
msgid "%s is stopped"
msgstr "%s は停止しています"

msgid "'node_staging_uri' is not set correctly. Could not load staging store."
msgstr ""
"'node_staging_uri' が正しく設定されていません。ステージングストアをロードでき"
"ませんでした。"

msgid "A body is not expected with this request."
msgstr "この要求では本文は予期されません。"

#, python-format
msgid ""
"A metadata definition object with name=%(object_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"name=%(object_name)s のメタデータ定義オブジェクトは、namespace="
"%(namespace_name)s に既に存在します。"

#, python-format
msgid ""
"A metadata definition property with name=%(property_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"name=%(property_name)s のメタデータ定義プロパティーは、namespace="
"%(namespace_name)s に既に存在します。"

#, python-format
msgid ""
"A metadata definition resource-type with name=%(resource_type_name)s already "
"exists."
msgstr ""
"name=%(resource_type_name)s のメタデータ定義リソースタイプは、既に存在しま"
"す。"

#, python-format
msgid ""
"A metadata tag with name=%(name)s already exists in namespace="
"%(namespace_name)s. (Please note that metadata tag names are case "
"insensitive)."
msgstr ""
"name=%(name)s のメタデータタグは既に namespace=%(namespace_name)s に存在しま"
"す。（メタデータのタグ名は大文字小文字を区別しないことに注意してください。）"

msgid "A set of URLs to access the image file kept in external store"
msgstr ""
"外部ストアに保持されているイメージファイルにアクセスするための一連の URL"

msgid "Amount of disk space (in GB) required to boot image."
msgstr "イメージのブートに必要なディスクスペースの量 (GB)"

msgid "Amount of ram (in MB) required to boot image."
msgstr "イメージのブートに必要な RAM の量 (MB)"

msgid "An identifier for the image"
msgstr "イメージの ID"

msgid "An identifier for the image member (tenantId)"
msgstr "イメージメンバーの ID (テナント ID)"

msgid "An identifier for the owner of this task"
msgstr "このタスクの所有者 ID"

msgid "An identifier for the task"
msgstr "タスクの ID"

msgid "An image file url"
msgstr "イメージファイルの URL"

msgid "An image schema url"
msgstr "イメージスキーマの URL"

msgid "An image self url"
msgstr "イメージ自体の URL"

msgid "An import task exception occurred"
msgstr "インポートタスクの例外が発生しました"

msgid "An object with the same identifier already exists."
msgstr "同じ ID のオブジェクトが既に存在します。"

msgid "An object with the same identifier is currently being operated on."
msgstr "現在、同じ ID を持つオブジェクトが操作されています。"

msgid "An object with the specified identifier was not found."
msgstr "指定された ID を持つオブジェクトが見つかりませんでした。"

msgid "An unknown exception occurred"
msgstr "不明な例外が発生しました"

msgid "An unknown task exception occurred"
msgstr "不明なタスク例外が発生しました"

#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr "重複したイメージのアップロードを試行します: %s"

#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "属性 '%(property)s' は読み取り専用です。"

#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "属性 '%(property)s' は予約されています。"

#, python-format
msgid "Attribute '%s' is read-only."
msgstr "属性 '%s' は読み取り専用です。"

#, python-format
msgid "Attribute '%s' is reserved."
msgstr "属性 '%s' は予約されています。"

msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""
"キューに入れられたイメージについてのみ属性 container_format を置換できます。"

msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""
"キューに入れられたイメージについてのみ属性 disk_format を置換できます。"

#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "URL %(url)s の認証サービスが見つかりません。"

#, python-format
msgid ""
"Authentication error - the token may have expired during file upload. "
"Deleting image data for %s."
msgstr ""
"認証エラー - トークンがファイルアップロード中に失効した可能性があります。 %s "
"へのイメージデータを削除します。"

msgid "Authorization failed."
msgstr "許可が失敗しました。"

msgid "Available categories:"
msgstr "使用可能カテゴリー:"

#, python-format
msgid "Bad \"%s\" query filter format. Use ISO 8601 DateTime notation."
msgstr ""
"正しくない \"%s\" 照会フィルター形式。ISO 8601 DateTime 表記を使用してくださ"
"い。"

#, python-format
msgid "Bad Command: %s"
msgstr "正しくないコマンド: %s"

#, python-format
msgid "Bad header: %(header_name)s"
msgstr "ヘッダーが正しくありません: %(header_name)s"

#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr "S3 URI の形式が正しくありません: %(uri)s"

#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr "Swift URI 内の資格情報 '%(creds)s' の形式が正しくありません"

msgid "Badly formed credentials in Swift URI."
msgstr "Swift URI 内の資格情報の形式が正しくありません。"

msgid "Body expected in request."
msgstr "要求の本体が必要です。"

msgid "Cannot be a negative value"
msgstr "負の値にすることはできません"

msgid "Cannot be a negative value."
msgstr "負の値にすることはできません。"

#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr "イメージ %(key)s '%(value)s' を整数に変換できません。"

msgid "Cannot remove last location in the image."
msgstr "イメージ内の最後の場所は削除できません。"

#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr "イメージ %(image_id)s のデータを保存できません: %(error)s"

msgid "Cannot set locations to empty list."
msgstr "空のリストに場所を設定することはできません。"

#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr ""
"チェックサムの検証に失敗しました。イメージ '%s' のキャッシュを打ち切りまし"
"た。"

msgid "Client disconnected before sending all data to backend"
msgstr "すべてのデータをバックエンドへ送信する前にクライアントが切断されました"

msgid "Command not found"
msgstr "コマンドが見つかりません"

msgid "Configuration option was not valid"
msgstr "構成オプションが無効でした"

#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr "接続エラー/URL %(url)s の認証サービスに対する正しくない要求。"

#, python-format
msgid "Constructed URL: %s"
msgstr "URL を構成しました: %s"

#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr "イメージ %(image_id)s のイメージダウンロードが壊れています"

#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr "30 秒間の試行後に %(host)s:%(port)s にバインドできませんでした"

msgid "Could not find OVF file in OVA archive file."
msgstr "OVA アーカイブファイル内に OVF ファイルが見つかりませんでした。"

#, python-format
msgid "Could not find metadata object %s"
msgstr "メタデータオブジェクト %s が見つかりませんでした"

#, python-format
msgid "Could not find metadata tag %s"
msgstr "メタデータタグ %s が見つかりませんでした"

#, python-format
msgid "Could not find namespace %s"
msgstr "名前空間 %s が見つかりませんでした"

#, python-format
msgid "Could not find property %s"
msgstr "プロパティー %s が見つかりませんでした"

msgid "Could not find required configuration option"
msgstr "必要な設定オプションが見つかりませんでした"

#, python-format
msgid "Could not find task %s"
msgstr "タスク %s が見つかりませんでした"

#, python-format
msgid "Could not update image: %s"
msgstr "イメージを更新できませんでした: %s"

#, python-format
msgid "Couldn't create metadata namespace: %s"
msgstr "メタデータ名前空間 %s を作成できませんでした"

#, python-format
msgid "Couldn't create metadata object: %s"
msgstr "メタデータオブジェクト %s を作成できませんでした"

#, python-format
msgid "Couldn't create metadata property: %s"
msgstr "メタデータプロパティ %s を作成できませんでした"

#, python-format
msgid "Couldn't create metadata tag: %s"
msgstr "メタデータタグ %s を作成できませんでした"

#, python-format
msgid "Couldn't update metadata namespace: %s"
msgstr "メタデータ名前空間 %s を更新できませんでした"

#, python-format
msgid "Couldn't update metadata object: %s"
msgstr "メタデータオブジェクト %s を更新できませんでした"

#, python-format
msgid "Couldn't update metadata property: %s"
msgstr "メタデータプロパティ %s を更新できませんでした"

#, python-format
msgid "Couldn't update metadata tag: %s"
msgstr "メタデータタグ %s を更新できませんでした"

msgid "Currently, OVA packages containing multiple disk are not supported."
msgstr "現在、複数のディスクを含む OVA パッケージはサポートされません。"

msgid "Custom property should not be greater than 255 characters."
msgstr "カスタムプロパティは 255 文字より大きくてはいけません。"

#, python-format
msgid "Data for image_id not found: %s"
msgstr "image_id のデータが見つかりません: %s"

msgid "Data supplied was not valid."
msgstr "指定されたデータが無効でした。"

msgid ""
"Database contraction did not run. Database contraction cannot be run before "
"data migration is complete. Run data migration using \"glance-manage db "
"migrate\"."
msgstr ""
"データベースの締結が実行されていません。データベースの締結はデータの移行が完"
"了する前には実行できません。まず、\"glance-manage db migrate\" を使用してデー"
"タの移行を実行してください。"

msgid ""
"Database contraction did not run. Database contraction cannot be run before "
"database expansion. Run database expansion first using \"glance-manage db "
"expand\""
msgstr ""
"データベースの締結が実行されていません。データベースの締結はデータベースの展"
"開の前には実行できません。まず、\"glance-manage db expand\" を使用してデータ"
"ベースの展開を実行してください。"

msgid ""
"Database contraction failed. Couldn't find head revision of contract branch."
msgstr ""
"データベースの締結に失敗しました。締結ブランチのヘッドリビジョンが見つかりま"
"せん。"

msgid ""
"Database expansion failed. Couldn't find head revision of expand branch."
msgstr ""
"データベースの展開に失敗しました。展開ブランチのヘッドリビジョンが見つかりま"
"せん。"

#, python-format
msgid ""
"Database expansion failed. Database expansion should have brought the "
"database version up to \"%(e_rev)s\" revision. But, current revisions are: "
"%(curr_revs)s "
msgstr ""
"データベースの展開に失敗しました。データベースの展開によって、データベースの"
"バージョンがリビジョン \"%(e_rev)s\" になっているはずです。 しかし、現在のリ"
"ビジョンは %(curr_revs)s です。"

msgid ""
"Database is either not under migration control or under legacy migration "
"control, please run \"glance-manage db sync\" to place the database under "
"alembic migration control."
msgstr ""
"データベースは移行制御下にも従来の移行制御下にもないため、\"glance-manage db "
"sync\" を実行して移行制御下に置いてください。"

msgid "Database is synced successfully."
msgstr "データベースの同期に成功しました。"

msgid "Database is up to date. No migrations needed."
msgstr "データベースは最新です。移行は必要ありません。"

msgid "Database is up to date. No upgrades needed."
msgstr "データベースは最新です。アップグレードは必要ありません。"

msgid "Date and time of image member creation"
msgstr "イメージメンバーの作成日時"

msgid "Date and time of image registration"
msgstr "イメージ登録日時"

msgid "Date and time of last modification of image member"
msgstr "イメージメンバーの最終変更日時"

msgid "Date and time of namespace creation"
msgstr "名前空間の作成日時"

msgid "Date and time of object creation"
msgstr "オブジェクトの作成日時"

msgid "Date and time of resource type association"
msgstr "リソースタイプ関連付けの日時"

msgid "Date and time of tag creation"
msgstr "タグの作成日時"

msgid "Date and time of the last image modification"
msgstr "イメージの最終変更日時"

msgid "Date and time of the last namespace modification"
msgstr "名前空間の最終変更日時"

msgid "Date and time of the last object modification"
msgstr "オブジェクトの最終変更日時"

msgid "Date and time of the last resource type association modification"
msgstr "リソースタイプ関連付けの最終変更日時"

msgid "Date and time of the last tag modification"
msgstr "タグの最終変更日時"

msgid "Datetime when this resource was created"
msgstr "このリソースが作成された日時"

msgid "Datetime when this resource was updated"
msgstr "このリソースが更新された日時"

msgid "Datetime when this resource would be subject to removal"
msgstr "このリソースが削除される日時"

#, python-format
msgid "Denying attempt to upload image because it exceeds the quota: %s"
msgstr ""
"イメージをアップロードしようとしましたが、割り当て量を超えてしまうため、拒否"
"されています: %s"

#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr "%d バイトより大きいイメージのアップロード試行を拒否しています。"

msgid "Descriptive name for the image"
msgstr "イメージの記述名"

#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""
"ドライバー %(driver_name)s を正しく設定できませんでした。理由: %(reason)s"

msgid ""
"Error decoding your request. Either the URL or the request body contained "
"characters that could not be decoded by Glance"
msgstr ""
"要求のデコードのエラー。URL または要求本文に Glance でデコードできない文字が"
"含まれていました。"

#, python-format
msgid "Error fetching members of image %(image_id)s: %(inner_msg)s"
msgstr "イメージ %(image_id)s のメンバーの取得中のエラー: %(inner_msg)s"

msgid "Error in store configuration. Adding images to store is disabled."
msgstr ""
"ストア設定にエラーがあります。ストアへのイメージの追加が無効になっています。"

msgid "Expected a member in the form: {\"member\": \"image_id\"}"
msgstr "次の形式でメンバーを予期: {\"member\": \"image_id\"}"

msgid "Expected a status in the form: {\"status\": \"status\"}"
msgstr "次の形式で状態を予期: {\"status\": \"status\"}"

#, python-format
msgid "Failed to add image metadata. Got error: %s"
msgstr "イメージメタデータを追加できませんでした。受け取ったエラー: %s"

#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr "削除するイメージ %(image_id)s が見つかりませんでした"

#, python-format
msgid "Failed to find resource type %(resourcetype)s to delete"
msgstr "削除するリソースタイプ %(resourcetype)s が見つかりませんでした"

#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr ""
"イメージキャッシュデータベースを初期化できませんでした。受け取ったエラー: %s"

#, python-format
msgid "Failed to read %s from config"
msgstr "設定から %s を読み取ることができませんでした"

#, python-format
msgid "Failed to sync database: ERROR: %s"
msgstr "データベースの同期に失敗しました: エラー: %s"

#, python-format
msgid "Failed to update image metadata. Got error: %s"
msgstr "イメージメタデータを更新できませんでした。エラー: %s"

#, python-format
msgid "Failed to upload image %s"
msgstr "イメージ %s をアップロードできませんでした"

#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""
"HTTP エラーが発生したため、イメージ %(image_id)s のイメージデータのアップロー"
"ドに失敗しました: %(error)s"

#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error: "
"%(error)s"
msgstr ""
"内部エラーが発生したため、イメージ %(image_id)s のイメージデータをアップロー"
"ドできませんでした: %(error)s"

#, python-format
msgid "File %(path)s has invalid backing file %(bfile)s, aborting."
msgstr ""
"ファイル %(path)s に無効なバッキングファイル %(bfile)s があります。打ち切りま"
"す。"

msgid ""
"File based imports are not allowed. Please use a non-local source of image "
"data."
msgstr ""
"ファイルベースのインポートは許可されません。イメージデータの非ローカルソース"
"を使用してください。"

msgid "Forbidden image access"
msgstr "イメージにアクセスする権限がありません"

#, python-format
msgid "Forbidden upload attempt: %s"
msgstr "禁止されているアップロードの試行: %s"

#, python-format
msgid "Forbidding request, metadata definition namespace=%s is not visible."
msgstr "要求は禁止されています。メタデータ定義 namespace=%s を表示できません"

#, python-format
msgid "Forbidding request, task %s is not visible"
msgstr "要求を禁止しています。タスク %s は表示されません"

msgid "Format of the container"
msgstr "コンテナーの形式"

msgid "Format of the disk"
msgstr "ディスクの形式"

#, python-format
msgid "Host \"%s\" is not valid."
msgstr "ホスト \"%s\" が無効です。"

#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr "ホストおよびポート \"%s\" が無効です。"

msgid ""
"Human-readable informative message only included when appropriate (usually "
"on failure)"
msgstr ""
"適切な場合 (通常は障害発生時) にのみ、人間が読み取れる情報メッセージが含まれ"
"ます"

msgid "If true, image will not be deletable."
msgstr "true の場合、イメージは削除可能になりません。"

msgid "If true, namespace will not be deletable."
msgstr "true の場合、名前空間は削除可能になりません。"

#, python-format
msgid "Image %(id)s could not be deleted because it is in use: %(exc)s"
msgstr "イメージ %(id)s は使用中のため削除できませんでした: %(exc)s"

#, python-format
msgid "Image %(id)s not found"
msgstr "イメージ %(id)s が見つかりません"

#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have been "
"deleted during the upload: %(error)s"
msgstr ""
"アップロード後にイメージ %(image_id)s が見つかりませんでした。このイメージは"
"アップロード中に削除された可能性があります: %(error)s"

#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr "イメージ %(image_id)s は保護されているため、削除できません。"

#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload, cleaning up the chunks uploaded."
msgstr ""
"アップロード後にイメージ %s が見つかりませんでした。イメージはアップロード中"
"に削除された可能性があります。アップロードされたチャンクをクリーンアップ中で"
"す。"

#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload."
msgstr ""
"アップロード後にイメージ %s が見つかりませんでした。このイメージはアップロー"
"ド中に削除された可能性があります。"

#, python-format
msgid "Image %s is deactivated"
msgstr "イメージ %s は非アクティブ化されています"

#, python-format
msgid "Image %s is not active"
msgstr "イメージ %s はアクティブではありません"

#, python-format
msgid "Image %s not found."
msgstr "イメージ %s が見つかりません。"

#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr "イメージがストレージクォータを超えています: %s"

msgid "Image id is required."
msgstr "イメージ ID が必要です。"

#, python-format
msgid "Image member limit exceeded for image %(id)s: %(e)s:"
msgstr "イメージ %(id)s のメンバー数がイメージメンバー上限を超えました: %(e)s:"

#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""
"%(cur_status)s から %(new_status)s へのイメージのステータス移行は許可されませ"
"ん"

#, python-format
msgid "Image storage media is full: %s"
msgstr "イメージストレージのメディアがフルです: %s"

#, python-format
msgid "Image tag limit exceeded for image %(id)s: %(e)s:"
msgstr "イメージ %(id)s のイメージタグ上限を超えました: %(e)s:"

#, python-format
msgid "Image upload problem: %s"
msgstr "イメージのアップロード問題: %s"

#, python-format
msgid "Image with identifier %s already exists!"
msgstr "ID %s のイメージは既に存在します。"

#, python-format
msgid "Image with identifier %s not found"
msgstr "ID %s のイメージが見つかりません"

#, python-format
msgid "Image with the given id %(image_id)s was not found"
msgstr "指定された ID %(image_id)s を持つイメージが見つかりませんでした"

msgid "Import request requires a 'method' field."
msgstr "インポートリクエストは、'method' フィールドが必要です。"

msgid "Import request requires a 'name' field."
msgstr "インポートリクエストは、'name' フィールドが必要です。"

#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"認証ストラテジーが誤っています。\"%(expected)s\" が必要ですが、\"%(received)s"
"\" を受け取りました"

#, python-format
msgid "Incorrect request: %s"
msgstr "正しくない要求: %s"

#, python-format
msgid "Input does not contain '%(key)s' field"
msgstr "入力に '%(key)s' フィールドが含まれていません"

#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr "イメージストレージのメディアに対する許可が不十分です: %s"

#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr "このリソースの JSON ポインターは無効です: '/%s'"

msgid "Invalid configuration in glance-swift conf file."
msgstr "glance-swift 設定ファイルの設定が無効です。"

msgid "Invalid configuration in property protection file."
msgstr "プロパティー保護ファイルで設定が無効です。"

#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "コンテンツタイプ %(content_type)s が無効です"

#, python-format
msgid "Invalid filter value %s. The quote is not closed."
msgstr "無効なフィルター値 %s。引用符が組みになっていません。"

#, python-format
msgid ""
"Invalid filter value %s. There is no comma after closing quotation mark."
msgstr "無効なフィルター値 %s。終了引用符の後にコンマがありません。"

#, python-format
msgid ""
"Invalid filter value %s. There is no comma before opening quotation mark."
msgstr "無効なフィルター値 %s。開始引用符の前にコンマがありません。"

msgid "Invalid image id format"
msgstr "イメージ ID の形式が無効です"

#, python-format
msgid "Invalid int value for max_rows: %(max_rows)s"
msgstr "max_rows の整数値 %(max_rows)s は無効です。"

msgid "Invalid location"
msgstr "無効な場所"

#, python-format
msgid "Invalid location: %s"
msgstr "無効な場所: %s"

#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""
"location_strategy オプションが無効です: %(name)s。有効なストラテジーオプショ"
"ン: %(strategies)s"

msgid "Invalid locations"
msgstr "無効な場所"

#, python-format
msgid "Invalid locations: %s"
msgstr "無効な場所: %s"

msgid "Invalid marker format"
msgstr "マーカーフォーマットが無効です"

msgid "Invalid marker. Image could not be found."
msgstr "無効なマーカーです。イメージが見つかりませんでした。"

#, python-format
msgid "Invalid membership association: %s"
msgstr "無効なメンバーシップの関連付け: %s"

#, python-format
msgid ""
"Invalid operation: `%(op)s`. It must be one of the following: %(available)s."
msgstr ""
"無効な操作: `%(op)s`。以下のいずれかでなければなりません: %(available)s。"

msgid "Invalid position for adding a location."
msgstr "場所の追加位置が無効です。"

msgid "Invalid position for removing a location."
msgstr "場所の削除位置が無効です。"

msgid "Invalid service catalog json."
msgstr "無効なサービスカタログ JSON ファイル。"

#, python-format
msgid "Invalid sort direction: %s"
msgstr "無効なソート方向: %s"

#, python-format
msgid ""
"Invalid sort key: %(sort_key)s. It must be one of the following: "
"%(available)s."
msgstr ""
"ソートキー %(sort_key)s は無効です。 %(available)s のいずれかでなければなりま"
"せん。"

#, python-format
msgid "Invalid status value: %s"
msgstr "状態の値が無効です: %s"

#, python-format
msgid "Invalid status: %s"
msgstr "無効な状況: %s"

#, python-format
msgid "Invalid type value: %s"
msgstr "タイプ値が無効です: %s"

#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition namespace "
"with the same name of %s"
msgstr ""
"無効な更新です。結果として、同じ名前 %s でメタデータ定義名前空間が重複しま"
"す。"

#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s  in namespace=%(namespace_name)s."
msgstr ""
"無効な更新です。結果として、同じ name=%(name)s で、namespace="
"%(namespace_name)s でメタデータ定義オブジェクトが重複します。"

#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"無効な更新です。結果として、同じ name=%(name)s で、namespace="
"%(namespace_name)s でメタデータ定義オブジェクトが重複します。"

#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition property "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"無効な更新です。結果として、同じ name=%(name)s で、namespace="
"%(namespace_name)s でメタデータ定義プロパティーが重複します。"

#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr "パラメーター '%(param)s' の値 '%(value)s' が無効です: %(extra_msg)s"

#, python-format
msgid ""
"Invalid value '%s' for 'protected' filter. Valid values are 'true' or "
"'false'."
msgstr ""
"'protected' フィルターの値 '%s' が無効です。許容される値は 'true' または "
"'false' です。"

#, python-format
msgid "Invalid value for option %(option)s: %(value)s"
msgstr "オプション %(option)s の値が無効です: %(value)s"

#, python-format
msgid "Invalid visibility value: %s"
msgstr "無効な可視性の値: %s"

#, python-format
msgid "It's not allowed to add locations if image status is %s."
msgstr "イメージの状態が %s の場合、場所を追加できません。"

msgid "It's not allowed to add locations if locations are invisible."
msgstr "場所が表示されない場合、場所を追加できません。"

#, python-format
msgid "It's not allowed to remove locations if image status is %s."
msgstr "イメージの状態が %s の場合、場所を削除できません。"

msgid "It's not allowed to remove locations if locations are invisible."
msgstr "場所が表示されない場合、場所を削除できません。"

#, python-format
msgid "It's not allowed to replace locations if image status is %s."
msgstr "イメージの状態が %s の場合、場所を変更できません。"

msgid "It's not allowed to update locations if locations are invisible."
msgstr "場所が表示されない場合、場所を更新できません。"

msgid "List of strings related to the image"
msgstr "イメージに関連する文字列のリスト"

msgid "Malformed JSON in request body."
msgstr "要求本体の JSON の形式が誤りです。"

msgid "Maximal age is count of days since epoch."
msgstr "最長存続時間は、エポック以降の日数です。"

#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "最大リダイレクト数 (%(redirects)s) を超えました。"

#, python-format
msgid "Member %(member_id)s is duplicated for image %(image_id)s"
msgstr "イメージ %(image_id)s のメンバー %(member_id)s が重複しています"

msgid "Member can't be empty"
msgstr "「メンバー」は空にできません"

msgid "Member to be added not specified"
msgstr "追加するメンバーが指定されていません"

msgid "Membership could not be found."
msgstr "メンバーシップが見つかりませんでした。"

#, python-format
msgid ""
"Metadata definition namespace %(namespace)s is protected and cannot be "
"deleted."
msgstr ""
"メタデータ定義名前空間 %(namespace)s は保護されており、削除できません。"

#, python-format
msgid "Metadata definition namespace not found for id=%s"
msgstr "id=%s のメタデータ定義名前空間が見つかりません"

#, python-format
msgid "Metadata definition namespace=%(namespace_name)s was not found."
msgstr ""
"namespace=%(namespace_name)s のメタデータ定義名前空間が見つかりませんでした。"

#, python-format
msgid ""
"Metadata definition object %(object_name)s is protected and cannot be "
"deleted."
msgstr ""
"メタデータ定義オブジェクト %(object_name)s は保護されており、削除できません。"

#, python-format
msgid "Metadata definition object not found for id=%s"
msgstr "id=%s のメタデータ定義オブジェクトが見つかりません"

#, python-format
msgid ""
"Metadata definition property %(property_name)s is protected and cannot be "
"deleted."
msgstr ""
"メタデータ定義プロパティー %(property_name)s は保護されており、削除できませ"
"ん。"

#, python-format
msgid "Metadata definition property not found for id=%s"
msgstr "id=%s のメタデータ定義プロパティーが見つかりません"

#, python-format
msgid ""
"Metadata definition resource-type %(resource_type_name)s is a seeded-system "
"type and cannot be deleted."
msgstr ""
"メタデータ定義リソースタイプ %(resource_type_name)s はシードシステムタイプで"
"あり、削除できません。"

#, python-format
msgid ""
"Metadata definition resource-type-association %(resource_type)s is protected "
"and cannot be deleted."
msgstr ""
"メタデータ定義リソースタイプ関連付け %(resource_type)s は保護されており、削除"
"できません。"

#, python-format
msgid ""
"Metadata definition tag %(tag_name)s is protected and cannot be deleted."
msgstr "メタデータ定義タグ %(tag_name)s は保護されており、削除できません。"

#, python-format
msgid "Metadata definition tag not found for id=%s"
msgstr "id=%s のメタデータ定義タグが見つかりません"

msgid "Minimal rows limit is 1."
msgstr "最少行数制限は 1 です。"

#, python-format
msgid "Missing required credential: %(required)s"
msgstr "必須の資格情報がありません: %(required)s"

#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally means "
"that a region is required and you have not supplied one."
msgstr ""
"領域 %(region)s に対して複数の「イメージ」サービスが一致します。これは一般"
"に、領域が必要であるのに、領域を指定していないことを意味します。"

msgid "Must supply a non-negative value for age."
msgstr "存続期間には負ではない値を指定してください。"

msgid "No authenticated user"
msgstr "認証されていないユーザー"

#, python-format
msgid "No image found with ID %s"
msgstr "ID が %s であるイメージは見つかりません"

#, python-format
msgid "No location found with ID %(loc)s from image %(img)s"
msgstr "イメージ %(img)s 内で ID が %(loc)s の場所は見つかりません"

msgid "No permission to share that image"
msgstr "そのイメージを共有する許可がありません"

#, python-format
msgid "Not allowed to create members for image %s."
msgstr "イメージ %s のメンバーの作成は許可されていません。"

#, python-format
msgid "Not allowed to deactivate image in status '%s'"
msgstr "状況が「%s」であるイメージの非アクティブ化は許可されていません"

#, python-format
msgid "Not allowed to delete members for image %s."
msgstr "イメージ %s のメンバーの削除は許可されていません。"

#, python-format
msgid "Not allowed to delete tags for image %s."
msgstr "イメージ %s のタグの削除は許可されていません。"

#, python-format
msgid "Not allowed to list members for image %s."
msgstr "イメージ %s のメンバーのリストは許可されていません。"

#, python-format
msgid "Not allowed to reactivate image in status '%s'"
msgstr "状況が「%s」であるイメージの再アクティブ化は許可されていません"

#, python-format
msgid "Not allowed to update members for image %s."
msgstr "イメージ %s のメンバーの更新は許可されていません。"

#, python-format
msgid "Not allowed to update tags for image %s."
msgstr "イメージ %s のタグの更新は許可されていません。"

#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr ""
"イメージ %(image_id)s ではイメージデータのアップロードは許可されません: "
"%(error)s"

msgid "Number of sort dirs does not match the number of sort keys"
msgstr "ソート方向の数がソートキーの数に一致しません"

msgid "OVA extract is limited to admin"
msgstr "OVA 抽出が実行できるのは管理者のみです"

msgid "Old and new sorting syntax cannot be combined"
msgstr "新旧のソート構文を結合することはできません"

msgid "Only shared images have members."
msgstr "共有イメージのみがメンバーを持ちます。"

#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr "操作 \"%s\" には \"value\" という名前のメンバーが必要です。"

msgid ""
"Operation objects must contain exactly one member named \"add\", \"remove\", "
"or \"replace\"."
msgstr ""
"操作オブジェクトには、\"add\"、\"remove\"、または \"replace\" という名前のメ"
"ンバーを正確に 1 つだけ含める必要があります。"

msgid ""
"Operation objects must contain only one member named \"add\", \"remove\", or "
"\"replace\"."
msgstr ""
"操作オブジェクトには、\"add\"、\"remove\"、または \"replace\" という名前のメ"
"ンバーを 1 つしか含められません。"

msgid "Operations must be JSON objects."
msgstr "操作は JSON オブジェクトでなければなりません。"

#, python-format
msgid "Original locations is not empty: %s"
msgstr "元の場所は空ではありません: %s"

msgid "Owner can't be updated by non admin."
msgstr "管理者以外は所有者を更新できません。"

msgid "Owner must be specified to create a tag."
msgstr "タグを作成するには、所有者を指定する必要があります。"

msgid "Owner of the image"
msgstr "イメージの所有者"

msgid "Owner of the namespace."
msgstr "名前空間の所有者。"

msgid "Param values can't contain 4 byte unicode."
msgstr "Param 値に 4 バイトの Unicode が含まれていてはなりません。"

msgid "Placed database under migration control at revision:"
msgstr "移行制御下にある配置されたデータベースはリビジョン:"

#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""
"ポインター `%s` に、認識されているエスケープシーケンスの一部ではない \"~\" が"
"含まれています。"

#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr "ポインター `%s` に隣接する \"/\" が含まれています。"

#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr "ポインター `%s` に有効なトークンが含まれていません。"

#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr "ポインター `%s` の先頭が \"/\" ではありません。"

#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr "ポインター `%s` の末尾が \"/\" です。"

#, python-format
msgid "Port \"%s\" is not valid."
msgstr "ポート \"%s\" が無効です。"

#, python-format
msgid "Process %d not running"
msgstr "プロセス %d は実行されていません"

#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr "データの保存前にプロパティー %s を設定する必要があります。"

#, python-format
msgid ""
"Property %(property_name)s does not start with the expected resource type "
"association prefix of '%(prefix)s'."
msgstr ""
"プロパティー %(property_name)s の先頭が、想定されるリソースタイプ関連付けのプ"
"レフィックス \"%(prefix)s\" ではありません。"

#, python-format
msgid "Property %s already present."
msgstr "プロパティー %s は既に存在しています。"

#, python-format
msgid "Property %s does not exist."
msgstr "プロパティー %s は存在しません。"

#, python-format
msgid "Property %s may not be removed."
msgstr "プロパティー %s は削除できません。"

#, python-format
msgid "Property %s must be set prior to saving data."
msgstr "データの保存前にプロパティー %s を設定する必要があります。"

msgid "Property names can't contain 4 byte unicode."
msgstr "プロパティー名に 4 バイトの Unicode が含まれていてはなりません。"

#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""
"指定されたオブジェクトがスキーマ '%(schema)s' と一致しません: %(reason)s"

#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr "指定されたタスク状況はサポートされていません: %(status)s"

#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr "指定されたタスクタイプはサポートされていません: %(type)s"

msgid "Provides a user friendly description of the namespace."
msgstr "分かりやすい名前空間の説明が提供されます。"

msgid "Purge command failed, check glance-manage logs for more details."
msgstr ""
"Purge コマンドが失敗しました。詳細は glance-manage のログを確認して下さい。"

msgid "Received invalid HTTP redirect."
msgstr "無効な HTTP リダイレクトを受け取りました。"

#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "許可のために %(uri)s にリダイレクトしています。"

#, python-format
msgid "Registry service can't use %s"
msgstr "レジストリーサービスでは %s を使用できません"

#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""
"レジストリーが API サーバーで正しく設定されていませんでした。理由: %(reason)s"

#, python-format
msgid "Reload of %(serv)s not supported"
msgstr "%(serv)s の再ロードはサポートされていません"

#, python-format
msgid "Reloading %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "%(serv)s (pid %(pid)s) をシグナル (%(sig)s) により再ロード中"

#, python-format
msgid "Removing stale pid file %s"
msgstr "失効した pid ファイル %s を削除中"

msgid "Request body must be a JSON array of operation objects."
msgstr "要求本文は、操作オブジェクトの JSON 配列でなければなりません。"

msgid "Request must be a list of commands"
msgstr "要求はコマンドのリストである必要があります"

msgid ""
"Resource type names should be aligned with Heat resource types whenever "
"possible: http://docs.openstack.org/developer/heat/template_guide/openstack."
"html"
msgstr ""
"可能であれば、リソースタイプ名を Heat リソースタイプと位置合わせします。"
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"

msgid "Response from Keystone does not contain a Glance endpoint."
msgstr "Keystone からの応答に Glance エンドポイントが含まれていません。"

msgid "Rolling upgrades are currently supported only for MySQL and Sqlite"
msgstr ""
"ローリングアップグレードは現在 MySQL と Sqlite のみがサポートされています。"

msgid "Scope of image accessibility"
msgstr "イメージのアクセス可能性の範囲"

msgid "Scope of namespace accessibility."
msgstr "名前空間アクセシビリティーの範囲。"

msgid "Scrubber encountered an error while trying to fetch scrub jobs."
msgstr "スクラブジョブの取得を試行中にエラーが発生しました。"

#, python-format
msgid "Server %(serv)s is stopped"
msgstr "サーバー %(serv)s は停止しています"

#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "サーバーワーカーの作成に失敗しました: %(reason)s"

msgid "Signature verification failed"
msgstr "シグニチャーの検証が失敗しました"

msgid "Size of image file in bytes"
msgstr "イメージファイルのサイズ (バイト)"

msgid ""
"Some resource types allow more than one key / value pair per instance.  For "
"example, Cinder allows user and image metadata on volumes. Only the image "
"properties metadata is evaluated by Nova (scheduling or drivers). This "
"property allows a namespace target to remove the ambiguity."
msgstr ""
"一部のリソースタイプでは、インスタンスごとに複数のキー/値のペアが許可されてい"
"ます。例えば、Cinder はボリューム上のユーザーおよびイメージメタデータを許可し"
"ています。イメージプロパティーメタデータのみ、Nova (スケジュールまたはドライ"
"バー) によって評価されます。このプロパティーによって、名前空間ターゲットから"
"あいまいさを排除できます。"

msgid "Sort direction supplied was not valid."
msgstr "指定されたソート方向が無効でした。"

msgid "Sort key supplied was not valid."
msgstr "指定されたソートキーが無効でした。"

msgid ""
"Specifies the prefix to use for the given resource type. Any properties in "
"the namespace should be prefixed with this prefix when being applied to the "
"specified resource type. Must include prefix separator (e.g. a colon :)."
msgstr ""
"指定されたリソースタイプに使用するプレフィックスを指定します。名前空間にある"
"プロパティーはすべて、指定されたリソースタイプに適用されるときに、このプレ"
"フィックスが先頭に付けられます。コロン (:) などのプレフィックス区切り文字を組"
"み込む必要があります。"

msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr "状況は、\"保留中\"、\"受諾\"、または\"拒否\" でなければなりません。"

msgid "Status not specified"
msgstr "状況が指定されていません"

msgid "Status of the image"
msgstr "イメージの状態"

#, python-format
msgid "Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr "%(cur_status)s から %(new_status)s への状況遷移は許可されません"

#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "%(serv)s (pid %(pid)s) をシグナル (%(sig)s) により停止中"

#, python-format
msgid "Store for image_id not found: %s"
msgstr "image_id のストアが見つかりません: %s"

#, python-format
msgid "Store for scheme %s not found"
msgstr "スキーマ %s のストアが見つかりません"

#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded image "
"(%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""
"指定された %(attr)s (%(supplied)s) とアップロードされたイメージ (%(actual)s) "
"から生成された %(attr)s が一致していませんでした。イメージの状況を「強制終了"
"済み」に設定します。"

msgid "Supported values for the 'container_format' image attribute"
msgstr "'container_format' イメージ属性に対してサポートされる値"

msgid "Supported values for the 'disk_format' image attribute"
msgstr "'disk_format' イメージ属性に対してサポートされる値"

#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr "%(serv)s として抑制された再作成は %(rsn)s でした。"

msgid "System SIGHUP signal received."
msgstr "システム SIGHUP シグナルを受信しました。"

#, python-format
msgid "Task '%s' is required"
msgstr "タスク '%s' が必要です"

msgid "Task does not exist"
msgstr "タスクが存在しません"

msgid "Task failed due to Internal Error"
msgstr "内部エラーが原因でタスクが失敗しました"

msgid "Task was not configured properly"
msgstr "タスクが正しく設定されませんでした"

#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr "指定された id %(task_id)s のタスクは見つかりませんでした"

msgid "The \"changes-since\" filter is no longer available on v2."
msgstr "\"changes-since\" フィルターは v2 上で使用できなくなりました。"

#, python-format
msgid "The CA file you specified %s does not exist"
msgstr "指定した CA ファイル %s は存在しません"

#, python-format
msgid ""
"The Image %(image_id)s object being created by this task %(task_id)s, is no "
"longer in valid status for further processing."
msgstr ""
"このタスク %(task_id)s で作成されているイメージ %(image_id)s オブジェクトは以"
"降の処理に有効な状況ではなくなりました。"

msgid "The Store URI was malformed."
msgstr "ストア URI の形式に誤りがありました。"

msgid ""
"The URL to the keystone service. If \"use_user_token\" is not in effect and "
"using keystone auth, then URL of keystone can be specified."
msgstr ""
"keystone サービスの URL。\"use_user_token\" が無効で、keystone 認証を使用して"
"いる場合、keystone の URL を指定できます。"

msgid ""
"The administrators password. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"管理者パスワード。\"use_user_token\" が無効であれば、管理資格情報を指定できま"
"す。"

msgid ""
"The administrators user name. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"管理者ユーザー名。\"use_user_token\" が無効であれば、管理資格情報を指定できま"
"す。"

#, python-format
msgid "The cert file you specified %s does not exist"
msgstr "指定した証明書ファイル %s は存在しません"

msgid "The current status of this task"
msgstr "このタスクの現行状況"

#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not "
"support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the cache "
"directory."
msgstr ""
"イメージキャッシュディレクトリー %(image_cache_dir)s が格納されているデバイス"
"では xattr はサポートされません。fstab を編集して、キャッシュディレクトリーが"
"格納されているデバイスの該当する行に user_xattr オプションを追加しなければな"
"らない可能性があります。"

#, python-format
msgid ""
"The given uri is not valid. Please specify a valid uri from the following "
"list of supported uri %(supported)s"
msgstr ""
"指定した URI が無効です。次のサポートされている URI のリストから、有効な URI "
"を指定してください: %(supported)s"

#, python-format
msgid "The image %s has data on staging"
msgstr "イメージ %s はステージングにデータがあります"

#, python-format
msgid ""
"The image %s is already present on the target, but our check for it did not "
"find it. This indicates that we do not have permissions to see all the "
"images on the target server."
msgstr ""
"イメージ %s は既にターゲット上にありますが、検査では見つかりませんでした。こ"
"れは、ターゲットサーバー上のすべてのイメージを表示する許可を持っていないこと"
"を示します。"

#, python-format
msgid "The incoming image is too large: %s"
msgstr "入力イメージが大きすぎます: %s"

#, python-format
msgid "The key file you specified %s does not exist"
msgstr "指定した鍵ファイル %s は存在しません"

#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"許可されるイメージの場所の数の制限を超えました。試行: %(attempted)s、最大: "
"%(maximum)s"

#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for this "
"image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"このイメージに対して許可されるイメージメンバー数の制限を超えました。試行: "
"%(attempted)s、最大: %(maximum)s"

#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"許可されるイメージプロパティー数の制限を超えました。試行: %(attempted)s、最"
"大: %(maximum)s"

#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. Attempted: "
"%(attempted)s, Maximum: %(maximum)s"
msgstr ""
"許可されるイメージタグ数の制限を超えました。試行: %(attempted)s、最大: "
"%(maximum)s"

#, python-format
msgid "The location %(location)s already exists"
msgstr "場所 %(location)s は既に存在します"

#, python-format
msgid "The location data has an invalid ID: %d"
msgstr "場所データの ID が無効です: %d"

#, python-format
msgid ""
"The metadata definition %(record_type)s with name=%(record_name)s not "
"deleted. Other records still refer to it."
msgstr ""
"name=%(record_name)s のメタデータ定義 %(record_type)s は削除されていません。"
"他のレコードがまだこのメタデータ定義を参照しています。"

#, python-format
msgid "The metadata definition namespace=%(namespace_name)s already exists."
msgstr "メタデータ定義 namespace=%(namespace_name)s は既に存在します。"

#, python-format
msgid ""
"The metadata definition object with name=%(object_name)s was not found in "
"namespace=%(namespace_name)s."
msgstr ""
"name=%(object_name)s のメタデータ定義オブジェクトが、namespace="
"%(namespace_name)s に見つかりませんでした。"

#, python-format
msgid ""
"The metadata definition property with name=%(property_name)s was not found "
"in namespace=%(namespace_name)s."
msgstr ""
"name=%(property_name)s のメタデータ定義プロパティーは、namespace="
"%(namespace_name)s に見つかりませんでした。"

#, python-format
msgid ""
"The metadata definition resource-type association of resource-type="
"%(resource_type_name)s to namespace=%(namespace_name)s already exists."
msgstr ""
"resource-type=%(resource_type_name)s の、namespace=%(namespace_name)s へのメ"
"タデータ定義リソースタイプ関連付けは、既に存在します。"

#, python-format
msgid ""
"The metadata definition resource-type association of resource-type="
"%(resource_type_name)s to namespace=%(namespace_name)s, was not found."
msgstr ""
"resource-type=%(resource_type_name)s の、namespace=%(namespace_name)s へのメ"
"タデータ定義リソースタイプ関連付けが見つかりませんでした。"

#, python-format
msgid ""
"The metadata definition resource-type with name=%(resource_type_name)s, was "
"not found."
msgstr ""
"name=%(resource_type_name)s のメタデータ定義リソースタイプが見つかりませんで"
"した。"

#, python-format
msgid ""
"The metadata definition tag with name=%(name)s was not found in namespace="
"%(namespace_name)s."
msgstr ""
"name=%(name)s のメタデータ定義タグが namespace=%(namespace_name)s に見つかり"
"ませんでした。"

msgid "The parameters required by task, JSON blob"
msgstr "タスクによって要求されるパラメーター、JSON blob"

msgid "The provided image is too large."
msgstr "指定されたイメージが大きすぎます。"

msgid ""
"The region for the authentication service. If \"use_user_token\" is not in "
"effect and using keystone auth, then region name can be specified."
msgstr ""
"認証サービスの領域。\"use_user_token\" が無効で、keystone 認証を使用している"
"場合、領域名を指定できます。"

msgid "The request returned 500 Internal Server Error."
msgstr "要求で「500 Internal Server Error」が返されました。"

msgid ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."
msgstr ""
"要求で「503 Service Unavailable」が返されました。これは一般に、サービスの過負"
"荷または他の一時的な障害時に起こります。"

#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that you "
"have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"要求が「302 Multiple Choices」を返しました。これは通常、要求 URI にバージョン"
"標識を含めなかったことを意味します。\n"
"\n"
"返された応答の本体:\n"
"%(body)s"

#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means "
"that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"要求で「413 Request Entity Too Large」が返されました。これは一般に、速度制限"
"または割り当て量のしきい値に違反したことを意味します。\n"
"\n"
"応答本体:\n"
"%(body)s"

#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"要求で予期しない状況が返されました: %(status)s。\n"
"\n"
"応答本体:\n"
"%(body)s"

msgid ""
"The requested image has been deactivated. Image data download is forbidden."
msgstr ""
"要求されたイメージは非アクティブ化されています。イメージデータのダウンロード"
"は禁止されています。"

msgid "The result of current task, JSON blob"
msgstr "現行タスクの結果、JSON blob"

#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""
"データのサイズ %(image_size)s が制限を超えます。%(remaining)s バイト残されて"
"います。"

#, python-format
msgid "The specified member %s could not be found"
msgstr "指定されたメンバー %s は見つかりませんでした"

#, python-format
msgid "The specified metadata object %s could not be found"
msgstr "指定されたメタデータオブジェクト %s は見つかりませんでした"

#, python-format
msgid "The specified metadata tag %s could not be found"
msgstr "指定されたメタデータタグ %s が見つかりませんでした"

#, python-format
msgid "The specified namespace %s could not be found"
msgstr "指定された名前空間 %s は見つかりませんでした"

#, python-format
msgid "The specified property %s could not be found"
msgstr "指定されたプロパティー %s は見つかりませんでした"

#, python-format
msgid "The specified resource type %s could not be found "
msgstr "指定されたリソースタイプ %s は見つかりませんでした"

msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'"
msgstr ""
"削除されたイメージの場所の状況は「pending_delete」または「deleted」にのみ設定"
"できます"

msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'."
msgstr ""
"削除されたイメージの場所の状況は「pending_delete」または「deleted」にのみ設定"
"できます。"

msgid "The status of this image member"
msgstr "このイメージメンバーの状況"

msgid ""
"The strategy to use for authentication. If \"use_user_token\" is not in "
"effect, then auth strategy can be specified."
msgstr ""
"認証に使用されるストラテジー。\"use_user_token\" が無効であれば、認証ストラテ"
"ジーを指定できます。"

#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr ""
"ターゲットメンバー %(member_id)s はイメージ %(image_id)s に既に関連付けられて"
"います。"

msgid ""
"The tenant name of the administrative user. If \"use_user_token\" is not in "
"effect, then admin tenant name can be specified."
msgstr ""
"管理ユーザーのテナント名。\"use_user_token\" が無効であれば、管理テナント名を"
"指定できます。"

msgid "The type of task represented by this content"
msgstr "このコンテンツによって表されるタスクのタイプ"

msgid "The unique namespace text."
msgstr "固有の名前空間テキスト。"

msgid "The user friendly name for the namespace. Used by UI if available."
msgstr "名前空間の分かりやすい名前。存在する場合は、UI によって使用されます。"

#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it.  Error: %(ioe)s"
msgstr ""
"%(error_key_name)s %(error_filename)s に関して問題があります。確認してくださ"
"い。エラー: %(ioe)s"

#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it. OpenSSL error: %(ce)s"
msgstr ""
"%(error_key_name)s %(error_filename)s に関して問題があります。確認してくださ"
"い。OpenSSL エラー: %(ce)s"

#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""
"ご使用の鍵ペアに関して問題があります。証明書 %(cert_file)s と鍵 %(key_file)s "
"がペアになっていることを確認してください。OpenSSL エラー %(ce)s"

msgid "There was an error configuring the client."
msgstr "クライアントの設定中にエラーが発生しました。"

msgid "There was an error connecting to a server"
msgstr "サーバーへの接続中にエラーが発生しました"

msgid ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."
msgstr ""
"この操作は、Glance タスクでは現在許可されていません。これらのタスクは、"
"expires_at プロパティーに基づき、時間に達すると自動的に削除されます。"

msgid ""
"Time in hours for which a task lives after, either succeeding or failing"
msgstr "成功または失敗の後でタスクが存続する時間 (時)"

msgid "Too few arguments."
msgstr "引数が少なすぎます。"

#, python-format
msgid ""
"Total size is %(size)d bytes (%(human_size)s) across %(img_count)d images"
msgstr ""
"合計サイズは、%(img_count)d) 個のイメージで %(size)d バイト (%(human_size)s) "
"です"

msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like swift://user:pass@http://authurl.com/v1/container/obj, "
"you need to change it to use the swift+http:// scheme, like so: swift+http://"
"user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI に複数回、スキームを指定することはできません。swift://user:pass@http://"
"authurl.com/v1/container/obj のような URI を指定した場合は、次のように、swift"
"+http:// スキームを使用するよう変更する必要があります。swift+http://user:"
"pass@authurl.com/v1/container/obj"

msgid "URL to access the image file kept in external store"
msgstr "外部ストアに保持されているイメージファイルにアクセスするための URL"

#, python-format
msgid ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""
"pid ファイル %(pid)s を作成できません。非ルートとして実行しますか?\n"
"一時ファイルにフォールバック中。次を使用して %(service)s サービスを\n"
"停止できます:  %(file)s %(server)s stop --pid-file %(fb)s"

#, python-format
msgid "Unable to filter by unknown operator '%s'."
msgstr "不明な演算子 '%s' によってフィルター処理を行うことができません。"

msgid "Unable to filter on a range with a non-numeric value."
msgstr "非数値を含む範囲ではフィルタリングできません。"

msgid "Unable to filter on a unknown operator."
msgstr "不明な演算子に対してフィルター処理を行うことができません。"

msgid "Unable to filter using the specified operator."
msgstr "指定された演算子を使用してフィルター処理ができません。"

msgid "Unable to filter using the specified range."
msgstr "指定された範囲ではフィルタリングできません。"

#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr "JSON スキーマの変更で '%s' が見つかりません"

#, python-format
msgid ""
"Unable to find `op` in JSON Schema change. It must be one of the following: "
"%(available)s."
msgstr ""
"JSON スキーマの変更で `op` が見つかりません。以下のいずれかでなければなりませ"
"ん: %(available)s。"

msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr "ファイル記述子制限を増加できません。非ルートとして実行しますか?"

#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"設定ファイル %(conf_file)s から %(app_name)s をロードできません。\n"
"受け取ったエラー: %(e)r"

#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "スキーマをロードできません: %(reason)s"

#, python-format
msgid "Unable to locate paste config file for %s."
msgstr "%s の paste 設定ファイルが見つかりません。"

#, python-format
msgid "Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""
"イメージ %(image_id)s の重複イメージデータはアップロードできません: %(error)s"

msgid "Unexpected body type. Expected list/dict."
msgstr "予期しない本文タイプ。予期されたのはリストまたは辞書です。"

#, python-format
msgid "Unexpected response: %s"
msgstr "予期しない応答: %s"

#, python-format
msgid "Unknown auth strategy '%s'"
msgstr "不明な認証ストラテジー '%s'"

#, python-format
msgid "Unknown command: %s"
msgstr "不明なコマンド: %s"

#, python-format
msgid "Unknown import method name '%s'."
msgstr "不明なインポートメソッド名 '%s' です。"

msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "ソート方向が不明です。'desc' または 'asc' でなければなりません"

msgid "Unrecognized JSON Schema draft version"
msgstr "認識されない JSON スキーマのドラフトバージョン"

msgid "Unrecognized changes-since value"
msgstr "認識されない changes-since 値"

#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr "サポートされない sort_dir です。許容値: %s"

#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr "サポートされない sort_key です。許容値: %s"

#, python-format
msgid "Upgraded database to: %(v)s, current revision(s): %(r)s"
msgstr ""
"データベースが %(v)s にアップグレードされました。現在のリビジョン: %(r)s"

msgid "Upgraded database, current revision(s):"
msgstr "データベースがアップグレードされました。現在のリビジョン:"

msgid "Virtual size of image in bytes"
msgstr "イメージの仮想サイズ (バイト)"

#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr "pid %(pid)s (%(file)s) が停止するまで 15 秒お待ちください。中断中です"

msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"サーバーを SSL モードで実行する場合は、cert_file オプション値と key_file オプ"
"ション値の両方を設定ファイルに指定する必要があります"

msgid ""
"Whether to pass through the user token when making requests to the registry. "
"To prevent failures with token expiration during big files upload, it is "
"recommended to set this parameter to False.If \"use_user_token\" is not in "
"effect, then admin credentials can be specified."
msgstr ""
"レジストリーに対して要求を行うときに、ユーザートークンをパススルーするかどう"
"か。サイズの大きなファイルのアップロード中のトークンの有効期限切れに伴う障害"
"を防ぐために、このパラメーターは False に設定することが推奨されま"
"す。\"use_user_token\" が無効である場合は、管理者のクレデンシャルを指定できま"
"す。"

#, python-format
msgid "Wrong command structure: %s"
msgstr "正しくないコマンド構造: %s"

msgid "You are not authenticated."
msgstr "認証されていません。"

#, python-format
msgid "You are not authorized to complete %(action)s action."
msgstr "%(action)s アクションの実行を許可されていません。"

msgid "You are not authorized to complete this action."
msgstr "このアクションの実行を許可されていません。"

#, python-format
msgid "You are not authorized to lookup image %s."
msgstr "イメージ %s を調べる権限がありません。"

#, python-format
msgid "You are not authorized to lookup the members of the image %s."
msgstr "イメージ %s のメンバーを調べる権限がありません。"

#, python-format
msgid "You are not permitted to create a tag in the namespace owned by '%s'"
msgstr "'%s' が所有する名前空間でのタグの作成は許可されていません"

msgid "You are not permitted to create image members for the image."
msgstr "そのイメージのイメージメンバーの作成は許可されていません。"

#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr "'%s' によって所有されているイメージの作成は許可されていません。"

#, python-format
msgid "You are not permitted to create namespace owned by '%s'"
msgstr "'%s' によって所有される名前空間の作成は許可されません"

#, python-format
msgid "You are not permitted to create object owned by '%s'"
msgstr "'%s' によって所有されるオブジェクトの作成は許可されません"

#, python-format
msgid "You are not permitted to create property owned by '%s'"
msgstr "'%s' によって所有されるプロパティーの作成は許可されません"

#, python-format
msgid "You are not permitted to create resource_type owned by '%s'"
msgstr "'%s' によって所有される resource_type の作成は許可されません"

#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr "所有者 %s を使用してこのタスクを作成することは許可されません"

msgid "You are not permitted to deactivate this image."
msgstr "このイメージの非アクティブ化は許可されていません。"

msgid "You are not permitted to delete this image."
msgstr "このイメージの削除は許可されていません。"

msgid "You are not permitted to delete this meta_resource_type."
msgstr "この meta_resource_type の削除は許可されません。"

msgid "You are not permitted to delete this namespace."
msgstr "この名前空間の削除は許可されません。"

msgid "You are not permitted to delete this object."
msgstr "このオブジェクトの削除は許可されません。"

msgid "You are not permitted to delete this property."
msgstr "このプロパティーの削除は許可されません。"

msgid "You are not permitted to delete this tag."
msgstr "このタグの削除は許可されていません。"

#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr "この %(resource)s 上の '%(attr)s' の変更は許可されません。"

#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr "このイメージ上の '%s' の変更は許可されません。"

msgid "You are not permitted to modify locations for this image."
msgstr "このイメージの場所の変更は許可されていません。"

msgid "You are not permitted to modify tags on this image."
msgstr "このイメージ上のタグの変更は許可されていません。"

msgid "You are not permitted to modify this image."
msgstr "このイメージの変更は許可されていません。"

msgid "You are not permitted to reactivate this image."
msgstr "このイメージの再アクティブ化は許可されていません。"

msgid "You are not permitted to set status on this task."
msgstr "このタスクに関する状況を設定することは許可されません。"

msgid "You are not permitted to update this namespace."
msgstr "この名前空間の更新は許可されません。"

msgid "You are not permitted to update this object."
msgstr "このオブジェクトの更新は許可されません。"

msgid "You are not permitted to update this property."
msgstr "このプロパティーの更新は許可されません。"

msgid "You are not permitted to update this tag."
msgstr "このタグの更新は許可されていません。"

msgid "You are not permitted to upload data for this image."
msgstr "このイメージのデータのアップロードは許可されていません。"

#, python-format
msgid "You cannot add image member for %s"
msgstr "%s のイメージメンバーを追加できません"

#, python-format
msgid "You cannot delete image member for %s"
msgstr "%s のイメージメンバーを削除できません"

#, python-format
msgid "You cannot get image member for %s"
msgstr "%s のイメージメンバーを取得できません"

#, python-format
msgid "You cannot update image member %s"
msgstr "イメージメンバー %s を更新できません"

msgid "You do not own this image"
msgstr "このイメージを所有していません"

msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert, "
"however you have failed to supply either a key_file parameter or set the "
"GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""
"接続時に SSL を使用するよう選択し、証明書を指定しましたが、key_file パラメー"
"ターを指定しなかったか、GLANCE_CLIENT_KEY_FILE 環境変数を設定しませんでした"

msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the "
"GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""
"接続時に SSL を使用するよう選択し、鍵を指定しましたが、cert_file パラメーター"
"を指定しなかったか、GLANCE_CLIENT_CERT_FILE 環境変数を設定しませんでした"

msgid ""
"Your database is not up to date. Your first step is to run `glance-manage db "
"expand`."
msgstr ""
"データベースが最新ではありません。最初のステップは、`glance-manage db "
"expand` です。"

msgid ""
"Your database is not up to date. Your next step is to run `glance-manage db "
"contract`."
msgstr ""
"データベースが最新ではありません。次のステップは、`glance-manage db "
"contract` です。"

msgid ""
"Your database is not up to date. Your next step is to run `glance-manage db "
"migrate`."
msgstr ""
"データベースが最新ではありません。次のステップは、`glance-manage db migrate` "
"です。"

msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"
msgstr ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"

#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr "__init__() で予期しないキーワード引数 '%s' が得られました"

#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted from_state="
"%(from)s)"
msgstr ""
"更新で %(current)s から %(next)s に移行できません (from_state=%(from)s が必"
"要)"

#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr "カスタムプロパティー (%(props)s) が基本プロパティーと競合しています"

msgid "eventlet 'poll' nor 'selects' hubs are available on this platform"
msgstr ""
"このプラットフォームでは eventlet の「poll」ハブも「selects」ハブも使用できま"
"せん"

msgid "is_public must be None, True, or False"
msgstr "is_public は、None、True、または False でなければなりません"

msgid "limit param must be an integer"
msgstr "limit パラメーターは整数でなければなりません"

msgid "limit param must be positive"
msgstr "limit パラメーターは正でなければなりません"

msgid "md5 hash of image contents."
msgstr "イメージコンテンツの MD5 ハッシュ。"

#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr "new_image() で予期しないキーワード %s が得られました"

msgid "protected must be True, or False"
msgstr "protected は True または False でなければなりません"

#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr "%(serv)s を起動できません。受け取ったエラー: %(e)s"

#, python-format
msgid "x-openstack-request-id is too long, max size %s"
msgstr "x-openstack-request-id が長すぎます。最大サイズは %s です"
